<?php

use Illuminate\Database\Seeder;

class insert_jra extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('jra_dokumens')->delete();

        $array = [
            ['id' => '1', 'kode' => 'DT', 'jenis_arsip' => 'Distribusi Dan Transportasi', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '0'],
            ['id' => '2', 'kode' => 'DT.00', 'jenis_arsip' => 'Transportir', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
        ['id' => '3', 'kode' => 'DT.00.01', 'jenis_arsip' => 'Evaluasi transpotir', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '4', 'kode' => 'DT.00.02', 'jenis_arsip' => 'Petunjuk Transportir', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '5', 'kode' => 'DT.00.03', 'jenis_arsip' => 'Pemberhentian Transportir', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '6', 'kode' => 'DT.01', 'jenis_arsip' => 'Distribusi & Transportasi Laut', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '7', 'kode' => 'DT.01.01', 'jenis_arsip' => 'Rencana Kebutuhan Penggunaan Kapal', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'musnah', 'level' => '2'],
['id' => '8', 'kode' => 'DT.01.02', 'jenis_arsip' => 'Rencana Realisasi Pemuatan barang', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '9', 'kode' => 'DT.01.03', 'jenis_arsip' => 'Time Sheet Dan Round Voyage', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '10', 'kode' => 'DT.01.04', 'jenis_arsip' => 'Berita Acara Bongkar', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '11', 'kode' => 'DT .02', 'jenis_arsip' => 'Distribusi Dan Transportasi Darat', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => '', 'level' => '1'],
['id' => '12', 'kode' => 'DT.02.01', 'jenis_arsip' => 'Rencana Kebutuhan Penggunaan Angkutan Darat', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '13', 'kode' => 'DT.02.02', 'jenis_arsip' => 'Permintaan Pemuatan Barang', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '14', 'kode' => 'DT.02.03', 'jenis_arsip' => 'Pengiriman Semen/Klinker', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '15', 'kode' => 'DT.02.04', 'jenis_arsip' => 'penerimaan Semen/Klinker', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '16', 'kode' => 'HK', 'jenis_arsip' => 'hukum', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '0'],
['id' => '17', 'kode' => 'HK.00', 'jenis_arsip' => 'Peraturan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '18', 'kode' => 'HK.00.01', 'jenis_arsip' => 'Peraturan Ektern', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '19', 'kode' => 'HK.00.02', 'jenis_arsip' => 'Peraturan Intern', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Permanen', 'level' => '2'],
['id' => '20', 'kode' => 'HK.01', 'jenis_arsip' => 'Tanah/Bangunan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '21', 'kode' => 'HK.01.01', 'jenis_arsip' => 'Pelepasan Hak', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
['id' => '22', 'kode' => 'HK.01.02', 'jenis_arsip' => 'Pemilikan & Pemakaian', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
['id' => '23', 'kode' => 'HK.02', 'jenis_arsip' => 'Surat Berharga', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '24', 'kode' => 'HK.02.01', 'jenis_arsip' => 'Akta', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
['id' => '25', 'kode' => 'HK.02.02', 'jenis_arsip' => 'Saham', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
['id' => '26', 'kode' => 'HK.02.03', 'jenis_arsip' => 'Piagam', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
['id' => '27', 'kode' => 'HK.02.04', 'jenis_arsip' => 'Bank Garansi', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '28', 'kode' => 'HK.03', 'jenis_arsip' => 'Dokumen Legal ', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '29', 'kode' => 'HK.03.01', 'jenis_arsip' => 'Sertifikasi', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Permanen', 'level' => '2'],
['id' => '30', 'kode' => 'HK.03.02', 'jenis_arsip' => 'Perjanjian/Kontrak', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
['id' => '31', 'kode' => 'HK.03.03', 'jenis_arsip' => 'Bantuan Hukum', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
['id' => '32', 'kode' => 'HK.03.04', 'jenis_arsip' => 'Perizinan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
['id' => '33', 'kode' => 'HK.03.05', 'jenis_arsip' => 'Logo Perusahaan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Permanen', 'level' => '2'],
['id' => '34', 'kode' => 'HM', 'jenis_arsip' => 'Humas', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '0'],
['id' => '35', 'kode' => 'HM.00', 'jenis_arsip' => 'Penerangan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '1'],
['id' => '36', 'kode' => 'HM.00.01', 'jenis_arsip' => 'Kegiatan Kepihak Luar', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '37', 'kode' => 'HM.00.02', 'jenis_arsip' => 'Kegiatan Kepihak Dalam', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '38', 'kode' => 'HM.01', 'jenis_arsip' => 'Protokoler', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '39', 'kode' => 'HM.01.01', 'jenis_arsip' => 'Kunjungan & Pelayanan Ke Pihak Luar', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '40', 'kode' => 'HM.01.02', 'jenis_arsip' => 'Kunjungan & Pelayanan Ke Pihak Dalam', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '41', 'kode' => 'HM.02', 'jenis_arsip' => 'Publikasi', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '42', 'kode' => 'HM.02.01', 'jenis_arsip' => 'Dokumentasi', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Permanen', 'level' => '2'],
['id' => '43', 'kode' => 'HM.02.02', 'jenis_arsip' => 'Penerbitan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '44', 'kode' => 'HM.03', 'jenis_arsip' => 'Rekanan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '45', 'kode' => 'HM.03.01', 'jenis_arsip' => 'Distributor', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '46', 'kode' => 'HM.03.02', 'jenis_arsip' => 'Suplier', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '47', 'kode' => 'HM.03.03', 'jenis_arsip' => 'Kontraktor', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '48', 'kode' => 'HM.03.04', 'jenis_arsip' => 'Ekspeditor', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '49', 'kode' => 'HM.03.05', 'jenis_arsip' => 'Lembaga Pemerintahan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '50', 'kode' => 'HM.04', 'jenis_arsip' => 'Bantuan Bima Lingkungan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '51', 'kode' => 'HM.04.01', 'jenis_arsip' => 'Sosial, Olah Raga Dan kesenian', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '52', 'kode' => 'HM.04.02', 'jenis_arsip' => 'Fisik/Sarana Umum', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '53', 'kode' => 'HM.04.03', 'jenis_arsip' => 'Pendidikan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '54', 'kode' => 'HM.04.04', 'jenis_arsip' => 'Ekonomi Masyarakat', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '55', 'kode' => 'HM.04.05', 'jenis_arsip' => 'Tenaga Kerja', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '56', 'kode' => 'HM.04.06', 'jenis_arsip' => 'Kesehatan Masyarakat Dan Bencana Alam', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '57', 'kode' => 'HM.05', 'jenis_arsip' => 'Kemitraan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '58', 'kode' => 'HM.05.01', 'jenis_arsip' => 'Pinjaman Modal Kerja', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '59', 'kode' => 'HM.05.02', 'jenis_arsip' => 'Pinjaman Khusus', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '60', 'kode' => 'HM.05.03', 'jenis_arsip' => 'Hibah', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '61', 'kode' => 'KK', 'jenis_arsip' => 'Keselamatan,Kesehatan Kerja & Lingkungan Hidup', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '0'],
['id' => '62', 'kode' => 'KK.00', 'jenis_arsip' => 'Identifikasi', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
['id' => '63', 'kode' => 'KK.00.01', 'jenis_arsip' => 'Peralatan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
['id' => '64', 'kode' => 'KK.00.02', 'jenis_arsip' => 'Bahan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '65', 'kode' => 'KK.00.03', 'jenis_arsip' => 'Proses', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '66', 'kode' => 'KK.00.04', 'jenis_arsip' => 'Lingkungan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '67', 'kode' => 'KK.01', 'jenis_arsip' => 'Penilaian', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '68', 'kode' => 'KK.01.01', 'jenis_arsip' => 'Tim K3LH/Tim PKTD', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '69', 'kode' => 'KK.01.02', 'jenis_arsip' => 'HKR', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '70', 'kode' => 'KK.00.03', 'jenis_arsip' => 'Bulan Mutu Dan Bulan K3', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '71', 'kode' => 'KK.02', 'jenis_arsip' => 'Pemantauan Dan Pengendalian', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '72', 'kode' => 'KK.02.01', 'jenis_arsip' => 'Kesehatan Kerja', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '73', 'kode' => 'KK.02.02', 'jenis_arsip' => 'Keselamatan Kerja', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Permanen', 'level' => '2'],
//['id' => '74', 'kode' => 'KK.02.03', 'jenis_arsip' => 'Lingkungan Hidup', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '75', 'kode' => 'KK.02.04', 'jenis_arsip' => 'Pelaksanaan P2K3', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '76', 'kode' => 'KM', 'jenis_arsip' => 'Keamanan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '0'],
//['id' => '77', 'kode' => 'KM.00', 'jenis_arsip' => 'Keamanan Lingkungan Intrn', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '1'],
//['id' => '78', 'kode' => 'KM.00.01', 'jenis_arsip' => 'Penyidikan/Pemeriksaan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '79', 'kode' => 'KM.00.02', 'jenis_arsip' => 'Barang Bukti', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '80', 'kode' => 'KM.01', 'jenis_arsip' => 'Keamanan lingkungan Ekstern', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '81', 'kode' => 'KM.01.01', 'jenis_arsip' => 'Penyidikan/Pemeriksaan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '82', 'kode' => 'KM.01.02', 'jenis_arsip' => 'Barang Bukti', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '83', 'kode' => 'KM.02', 'jenis_arsip' => 'Kerja Sama Dengan Aparat Hukum', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '84', 'kode' => 'KM.03', 'jenis_arsip' => 'Koordinasi Keamanan Pemerintahan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '1'],
//['id' => '85', 'kode' => 'KS', 'jenis_arsip' => 'Kesekretariatan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '0'],
//['id' => '86', 'kode' => 'KS.00', 'jenis_arsip' => 'Surat Munyurat', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '87', 'kode' => 'KS.00.01', 'jenis_arsip' => 'Pihak Luar', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '88', 'kode' => 'KS.00.02', 'jenis_arsip' => 'Pihak Dalam', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '89', 'kode' => 'KS.01', 'jenis_arsip' => 'Laporan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '90', 'kode' => 'KS.01.01', 'jenis_arsip' => 'Laporan Kinerja Bulanan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '91', 'kode' => 'KS.01.02', 'jenis_arsip' => 'Laporan Kinerja Tahunan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Permanen', 'level' => '2'],
//['id' => '92', 'kode' => 'KS.01.03', 'jenis_arsip' => 'Prognosa', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '93', 'kode' => 'KS.02', 'jenis_arsip' => 'Kearsipan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '94', 'kode' => 'KS.02.01', 'jenis_arsip' => 'Pengelolaan Arsip Aktif', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '95', 'kode' => 'KS.02.02', 'jenis_arsip' => 'Penyerahan Arsip Inaktif ke Sentral Akrsip', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '96', 'kode' => 'KS.02.03', 'jenis_arsip' => 'Penyerahan Arsip Ke Arsip Nasional', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '97', 'kode' => 'KS.02.04', 'jenis_arsip' => 'Pemeliharaan Arsip', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '98', 'kode' => 'KS.02.05', 'jenis_arsip' => 'Pemusnahan Arsip', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Permanen', 'level' => '2'],
//['id' => '99', 'kode' => 'KS.03', 'jenis_arsip' => 'Suplies Kantor', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '100', 'kode' => 'KS.03.01', 'jenis_arsip' => 'Penjilidan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '101', 'kode' => 'KS.03.02', 'jenis_arsip' => 'Foto Copy', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '102', 'kode' => 'KS,03.03', 'jenis_arsip' => 'Percetakan Identitas', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '103', 'kode' => 'KS.03.04', 'jenis_arsip' => 'Alat Tulis Kantor (ATK)', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '104', 'kode' => 'KS.03.05', 'jenis_arsip' => 'Perpustakaan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '105', 'kode' => 'KU', 'jenis_arsip' => 'Keuangan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '0'],
//['id' => '106', 'kode' => 'KU.00', 'jenis_arsip' => 'Anggaran', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '1'],
//['id' => '107', 'kode' => 'KU.00.01', 'jenis_arsip' => 'Rencana Kerja & Anggaran Perusahaan Tahunan RKAP', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Permanen', 'level' => '2'],
//['id' => '108', 'kode' => 'KU.01', 'jenis_arsip' => 'Perbendaharaan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '109', 'kode' => 'KU.01.01', 'jenis_arsip' => 'Kas Bank', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '110', 'kode' => 'KU.01.02', 'jenis_arsip' => 'Hutang', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '111', 'kode' => 'KU.01.03', 'jenis_arsip' => 'Piutang', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '112', 'kode' => 'KU.01.04', 'jenis_arsip' => 'Pajak', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '113', 'kode' => 'KU.01.05', 'jenis_arsip' => 'Asuransi', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '114', 'kode' => 'KU.02', 'jenis_arsip' => 'Akuntansi', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '115', 'kode' => 'KU.02.01', 'jenis_arsip' => 'Laporan Keuangan  ', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Permanen', 'level' => '2'],
//['id' => '116', 'kode' => 'KU.02.02', 'jenis_arsip' => 'Pencatatan Transaksi', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '117', 'kode' => 'KU.02.03', 'jenis_arsip' => 'Perhitungan Harga Pokok', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '118', 'kode' => 'KU.02.04', 'jenis_arsip' => 'Aktiva Tetap', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '119', 'kode' => 'KU.02.05', 'jenis_arsip' => 'Rekonsiliasi', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '120', 'kode' => 'LB', 'jenis_arsip' => 'Penelitian Dan Pengembangan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '0'],
//['id' => '121', 'kode' => 'LB.00', 'jenis_arsip' => 'Penelitian', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '122', 'kode' => 'LB.00.01', 'jenis_arsip' => 'Survey/Penelitian', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '123', 'kode' => 'LB.00.02', 'jenis_arsip' => 'Study Kelayakan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '124', 'kode' => 'LB.00.03', 'jenis_arsip' => 'Aplikasi Produk', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '125', 'kode' => 'LB.01', 'jenis_arsip' => 'Rancang Bangun', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '126', 'kode' => 'LB.01.01', 'jenis_arsip' => 'Rancang Peralatan Utama Pabrik', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '127', 'kode' => 'LB.01.02', 'jenis_arsip' => 'Rancang Peralatan Penunjang Pabrik', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '128', 'kode' => 'LB.01.03', 'jenis_arsip' => 'Rancang Sarana & Prasarana', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '129', 'kode' => 'LB.02', 'jenis_arsip' => 'Pengembangan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '130', 'kode' => 'LB.02.01', 'jenis_arsip' => 'In Bound/ Logistic Manajement', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '131', 'kode' => 'LB.02.02', 'jenis_arsip' => 'Berbelanja Modal (Capex Manajemen)', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '132', 'kode' => 'LB.02.03', 'jenis_arsip' => 'Capacity Management', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '133', 'kode' => 'LB.02.04', 'jenis_arsip' => 'Cost Management', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '134', 'kode' => 'LB.02.05', 'jenis_arsip' => 'Quality Assurance', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '135', 'kode' => 'LB.02.06', 'jenis_arsip' => 'Inovation', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Vital', 'level' => '2'],
//['id' => '136', 'kode' => 'MR', 'jenis_arsip' => 'Manajemen Risiko', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '0'],
//['id' => '137', 'kode' => 'MR.00', 'jenis_arsip' => 'Manajemen Risiko', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '1'],
//['id' => '138', 'kode' => 'PB', 'jenis_arsip' => 'Perbekalan', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '0'],
//['id' => '139', 'kode' => 'PB.00', 'jenis_arsip' => 'Kinerja Suplier', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '140', 'kode' => 'PB.00.01', 'jenis_arsip' => 'Data Vendor', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '141', 'kode' => 'PB.00.02', 'jenis_arsip' => 'Penunjukan Vendor', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '142', 'kode' => 'PB.00.03', 'jenis_arsip' => 'Evaluasi Vendor', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '143', 'kode' => 'PB.01', 'jenis_arsip' => 'Pengadaan Barang', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '144', 'kode' => 'PB.01.01', 'jenis_arsip' => 'Barang Umum Dan Inventaris', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '145', 'kode' => 'PB.01.02', 'jenis_arsip' => 'Barang Suku Cadang', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],
//['id' => '146', 'kode' => 'PB.01.03', 'jenis_arsip' => 'operating Suplies', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '147', 'kode' => 'PB.02', 'jenis_arsip' => 'Pengadaan Jasa', 'waktu_aktif' => '', 'waktu_inaktif' => '', 'keterangan' => '', 'level' => '1'],
//['id' => '148', 'kode' => 'PB.02.01', 'jenis_arsip' => 'Jasa Angkutan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Musnah', 'level' => '2'],
//['id' => '149', 'kode' => 'PB.02.02', 'jenis_arsip' => 'Jasa Pekerjaan', 'waktu_aktif' => '10', 'waktu_inaktif' => '8', 'keterangan' => 'Dinilai Kembali', 'level' => '2'],

        ];

        DB::table('jra_dokumens')->insert($array);
    }
}
